"use client";

import { useRouter } from "next/navigation";

import { CreateView } from "@/components/patterns/create-view";
import { CourseForm } from "@/components/views/courses/course-form";
import { notify } from "@/components/notifications/toast-helpers";
import { ROUTES } from "@/lib/constants";

export default function NewCoursePage() {
  const router = useRouter();

  const handleSubmit = async (
    values: {
      name: string;
      code: string;
      subjectId: number;
      lecturerId: string;
      description: string;
    },
    cover: {
      url: string;
      publicId: string;
    } | null
  ) => {
    // TODO: replace with a real API call when backend exists
    await new Promise((r) => setTimeout(r, 800));

    // Preview the payload shape the real API will receive
    console.log("[create course] payload:", {
      ...values,
      coverUrl: cover?.url,
      coverCldPubId: cover?.publicId,
      joinCode: "AUTO", // placeholder — real code generated by backend later
    });

    notify.success("Course created", `${values.name} has been added.`);
    router.push(ROUTES.COURSES);
  };

  return (
    <CreateView
      title="Create course"
      description="Add a new course to the catalog."
      breadcrumbs={[
        { label: "Courses", href: ROUTES.COURSES },
        { label: "Create" },
      ]}
      backHref={ROUTES.COURSES}
    >
      <div className="max-w-3xl">
        <CourseForm mode="create" onSubmit={handleSubmit} />
      </div>
    </CreateView>
  );
}